### ISSUE TITLE
Download finetuned models

### ISSUE THREAD

**Issue by flackbash** [shavarani/SpEL#11]
Hello,

I'm excited to try out SpEL, reproduce the reported results and also evaluate it over additional benchmarks.

From the README, however, I'm not sure whether there is a way to use SpEL for inference without having to train or fine-tune the model myself (which would be great, as I only have limited access to GPUs).
As far as I understand, the download links only provide the data necessary for fine-tuning the model (which is automatically downloaded when running the fine-tuning script) and not the final fine-tuned model?

Without downloading anything and without running the fine-tuning scripts, I tried to run the provided code snippet from the README after installing the requirements and adding the src directory to the python path, but I get an error:

```
Traceback (most recent call last):
  File "/local/data/prangen/src/SpEL/test.py", line 2, in <module>
    from spel.model import SpELAnnotator
  File "/local/data/prangen/src/SpEL/src/spel/model.py", line 18, in <module>
    from spel.utils import store_validation_data_wiki, chunk_annotate_and_merge_to_phrase, \
  File "/local/data/prangen/src/SpEL/src/spel/utils.py", line 13, in <module>
    from spel.data_loader import get_dataset, tokenizer, dl_sa
  File "/local/data/prangen/src/SpEL/src/spel/data_loader.py", line 52, in <module>
    BERT_MODEL_NAME = get_base_model_name()
  File "/local/data/prangen/src/SpEL/src/spel/configuration.py", line 14, in get_base_model_name
    return open("base_model.cfg", "r").read().strip()
FileNotFoundError: [Errno 2] No such file or directory: 'base_model.cfg'
```
Any clarification is much appreciated!

**Comment by shavarani** [comment]
Hi and thank you for checking out our work.

The `No such file or directory: 'base_model.cfg'` error shows that you are running the code from a directory that does not have access to `https://github.com/shavarani/SpEL/blob/main/src/spel/base_model.cfg`. To fix this, you only need to copy the original `base_model.cfg` (`https://github.com/shavarani/SpEL/blob/main/src/spel/base_model.cfg`) file into your current directory and the code should be good to go.

> As far as I understand, the download links only provide the data necessary for fine-tuning the model (which is automatically downloaded when running the fine-tuning script) and not the final fine-tuned model?

We have provided the download links both to the data and finetuned models. The models are both linked in the README file of this repository and on huggingface: https://huggingface.co/shavarani/SpEL/tree/main/
You will, however, not need to download them manually, if you run any of the provided evaluation scripts including the sample script, the could should automatically download all the necessary files.

Please let us know if the issue is not resolved or you need further troubleshooting.

**Comment by flackbash** [comment]
Thanks a lot for the clarifications, it's all working fine now :)
